# Use an official Node.js runtime as a parent image
FROM node

# Set the working directory in the container
WORKDIR /app

# Copy the rest of the application code
COPY . .

# Install dependencies
RUN npm install

# Build the application
RUN npm run build

# Expose port (if you're running a development server)
EXPOSE 8080

# Command to run when the container starts
CMD ["npm", "start"]
